disabled_rules:
  - force_cast
  - force_try
  - line_length
  - trailing_comma
  - statement_position
  - for_where
  - identifier_name

opt_in_rules:
  - inclusive_language
  - redundant_optional_initialization
  - unused_imports

type_name:
  min_length: 2

excluded:
  - .build
