#!/bin/bash
# Usage: scripts/generate-secrets.sh
# Reads .env from project root, writes Sources/Glint/Sources/GoogleSecrets.swift

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR/.."
ENV_FILE="$ROOT/.env"
OUTPUT="$ROOT/Sources/Glint/Sources/GoogleSecrets.swift"

if [ ! -f "$ENV_FILE" ]; then
    echo "::warning:: .env not found at $ENV_FILE — using placeholder secrets"
    echo "Copy .env.example to .env and fill in your values."
    # Generate with placeholders so build doesn't fail
    CLIENT_ID="placeholder_client_id"
    CLIENT_SECRET="placeholder_client_secret"
else
    source "$ENV_FILE"
    CLIENT_ID="${GOOGLE_CLIENT_ID:-placeholder_client_id}"
    CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-placeholder_client_secret}"
fi

cat > "$OUTPUT" <<EOF
// Auto-generated by scripts/generate-secrets.sh — do not edit
enum GoogleSecrets {
    static let clientId = "$CLIENT_ID"
    static let clientSecret = "$CLIENT_SECRET"
}
EOF
